### ISSUE TITLE
TypeError: Object Table already exists

### ISSUE THREAD

**Issue by Alua-Kinzhebayeva** [obie/saws#2]
Thanks for the awesome library!
I am using saws  v0.0.7 in lambda function developed and deployed with serverless.
I am trying to save records into DynamoDB. I copied and pasted the example from ReadMe.
On the first run, tables gets created and a record gets inserted.
But if I run lambda twice (I change "IdentityId": "id0000003", "StripeCustomerId": "cus_00000003", redeploy and then run again), I get "TypeError: Object Table already exists". Is it an intended behaviour?
```
module.exports.respond = function(event, cb) {
  var STRIPE_CUSTOMERS_PARAMS = {
    TableName: "StripeCustomers",
    KeySchema: [
      {AttributeName: 'IdentityId', KeyType: 'HASH'},
    ],
    AttributeDefinitions: [
      {AttributeName: 'IdentityId', AttributeType: 'S'}
    ],
    ProvisionedThroughput: { ReadCapacityUnits: 2, WriteCapacityUnits: 1 }
  };

  var customers = new Saws.Table(STRIPE_CUSTOMERS_PARAMS);
  customers.save({
    "IdentityId": "id0000003",
    "StripeCustomerId": "cus_00000003"
  }, function(err, data) {
      if(!err){
        return cb(null, JSON.stringify(data));
      }else{
        return cb(err);
      }
  });
};
```

```
2016-01-13T11:07:32.955Z	d738c827-b9e5-11e5-af2a-bfa0d42aea3a	TypeError: Object Table already exists: StripeCustomers-dev has no method 'includes' at Response.<anonymous> (/var/task/modules/notification/node_modules/saws/lib/saws.js:41:35) at Request.<anonymous> (/var/task/modules/notification/node_modules/aws-sdk/lib/request.js:354:18) at Request.callListeners (/var/task/modules/notification/node_modules/aws-sdk/lib/sequential_executor.js:105:20) at Request.emit (/var/task/modules/notification/node_modules/aws-sdk/lib/sequential_executor.js:77:10) at Request.emit (/var/task/modules/notification/node_modules/aws-sdk/lib/request.js:596:14) at Request.transition (/var/task/modules/notification/node_modules/aws-sdk/lib/request.js:21:10) at AcceptorStateMachine.runTo (/var/task/modules/notification/node_modules/aws-sdk/lib/state_machine.js:14:12) at /var/task/modules/notification/node_modules/aws-sdk/lib/state_machine.js:26:10 at Request.<anonymous> (/var/task/modules/notification/node_modules/aws-sdk/lib/request.js:37:9) at Request.<anonymous> (/var/task/modules/notification/node_modules/aws-sdk/lib/request.js:598:12)
```
https://gyazo.com/3248b6c1fbfa666cdb2645809b128fc6

**Comment by Alua-Kinzhebayeva** [comment]
I think I got it. AWS node.js runtime has problems with 'includes'
```
if(err && err.message.includes('Table already exists')) {
```

**Comment by Alua-Kinzhebayeva** [comment]
I fixed the issue with a polyfill. It works now.
```
if (!String.prototype.includes) {
  String.prototype.includes = function() {
    'use strict';
    return String.prototype.indexOf.apply(this, arguments) !== -1;
  };
}
```

**Comment by lpinca** [comment]
@Alua-Kinzhebayeva `String.prototype.includes()` is in the ES2015 specifications, using a polyfill is workaround, not a fix.
If this library uses ES2015 features, it should specify which versions of node are supported using the [`engines`](https://docs.npmjs.com/files/package.json#engines) field or use a transpiler like babel.

AWS Lambda uses node [`v0.10.36`](http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html), which is pretty sad.

**Comment by Alua-Kinzhebayeva** [comment]
@lpinca, thanks, I already know that. I just called 'fix', and yes, I know it is not a 'proper' fix
